[book]
authors = ["CompEng0001"]
language = "en"
src = "src"
title = "mdbook-gitinfo"

[output.html]
git-repository-url = "https://github.com/compeng0001/mdbook-gitinfo"
edit-url-template = "https://github.com//compeng0001/mdbook-gitinfo/edit/main/{path}"
additional-css = ["theme/gitinfo.css"]

[output.html.print]
enable = false

[preprocessor.gitinfo]
enable = true
header = true
footer = true
message.header = "Last updated: <em>{{date}}</em>"
message.footer = "branch: {{branch}} {{sep}} commit: {{hash}} {{sep}} tag: {{tag}}"
align.header = "center"
align.footer = "center"
margin.header.top = "2em"
margin.header.bottom = "2em"
margin.footer = ["2em", "0", "0", "0"]
font-size = "0.8em"
separator = "||"
date-format = "%A %d %B %Y"
time-format = "@ %H:%M:%S"
branch = "main"
hyperlink = true
contributors = true
